### ISSUE TITLE
multiple score insert

### ISSUE THREAD

**Issue by jan-pfr** [DomenicDev/SET08114_cw#1]
After a fail your score is displayed. When you directly retry and die again without collecting coins, the last score is displayed again and is also in the scoreboard. When you start a new game from the main menu and die without collection coins, the bug is not taking place.

**Comment by DomenicDev** [comment]
Hello @jan-pfr thank you for reporting that bug. I will look into it and try to fix it as soon as possible.

**Comment by DomenicDev** [comment]
This bug will be fixed with the next version. Thanks again for reporting :-)
